server:
  port: 8080
  servlet:
    context-path:

spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

  #devtools热部署
  devtools:
    restart:
      enabled: true
  #页面不加载缓存，修改即时生效
  thymeleaf:
    cache: false


