server:
  port: 8081
spring:
  profiles:
    active: dev

---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: prod

#person:
#    lastName: zhangsan
#    age: 18
#    boss: false
#    birth: 2019/9/13
#    maps: {k1: v1,k2: v2,k3: v3}
#    lists:
#      - lisi
#      - zhaoliu
#    dog:
#      name: 小狗
#      age: 2